export const VIOLATION_STATUS = {
  REPORTED: 'reported', VERIFIED: 'verified',
  COURTESY_NOTICE_SENT: 'courtesy_notice_sent', FORMAL_NOTICE_SENT: 'formal_notice_sent',
  ESCALATED: 'escalated', HEARING_SCHEDULED: 'hearing_scheduled',
  FINE_ASSESSED: 'fine_assessed', PAYMENT_PLAN: 'payment_plan',
  LIEN_FILED: 'lien_filed', LEGAL_REFERRAL: 'legal_referral',
  RESOLVED_CURED: 'resolved_cured', RESOLVED_PAID: 'resolved_paid', DISMISSED: 'dismissed',
} as const;
export type ViolationStatus = (typeof VIOLATION_STATUS)[keyof typeof VIOLATION_STATUS];
export const TERMINAL_STATES: readonly ViolationStatus[] = [
  VIOLATION_STATUS.RESOLVED_CURED, VIOLATION_STATUS.RESOLVED_PAID,
  VIOLATION_STATUS.DISMISSED, VIOLATION_STATUS.LEGAL_REFERRAL,
] as const;
export const VALID_TRANSITIONS: Record<string, readonly ViolationStatus[]> = {
  [VIOLATION_STATUS.REPORTED]: [VIOLATION_STATUS.VERIFIED, VIOLATION_STATUS.DISMISSED],
  [VIOLATION_STATUS.VERIFIED]: [VIOLATION_STATUS.COURTESY_NOTICE_SENT, VIOLATION_STATUS.DISMISSED],
  [VIOLATION_STATUS.COURTESY_NOTICE_SENT]: [VIOLATION_STATUS.FORMAL_NOTICE_SENT, VIOLATION_STATUS.RESOLVED_CURED],
  [VIOLATION_STATUS.FORMAL_NOTICE_SENT]: [VIOLATION_STATUS.ESCALATED, VIOLATION_STATUS.HEARING_SCHEDULED, VIOLATION_STATUS.RESOLVED_CURED],
  [VIOLATION_STATUS.ESCALATED]: [VIOLATION_STATUS.HEARING_SCHEDULED, VIOLATION_STATUS.RESOLVED_CURED],
  [VIOLATION_STATUS.HEARING_SCHEDULED]: [VIOLATION_STATUS.FINE_ASSESSED, VIOLATION_STATUS.DISMISSED, VIOLATION_STATUS.RESOLVED_CURED],
  [VIOLATION_STATUS.FINE_ASSESSED]: [VIOLATION_STATUS.PAYMENT_PLAN, VIOLATION_STATUS.LIEN_FILED, VIOLATION_STATUS.RESOLVED_PAID],
  [VIOLATION_STATUS.PAYMENT_PLAN]: [VIOLATION_STATUS.RESOLVED_PAID, VIOLATION_STATUS.LIEN_FILED],
  [VIOLATION_STATUS.LIEN_FILED]: [VIOLATION_STATUS.LEGAL_REFERRAL, VIOLATION_STATUS.RESOLVED_PAID],
} as const;
