import { sql } from 'drizzle-orm';
import {
  pgTable, uuid, bigint, text, integer, smallint, numeric,
  boolean, jsonb, timestamp, date, varchar, char, unique,
} from 'drizzle-orm/pg-core';
import { tenants, users } from './platform';

export const communities = pgTable('communities', {
  id: uuid('id').defaultRandom().primaryKey(),
  tenantId: bigint('tenant_id', { mode: 'number' }).notNull().references(() => tenants.id),
  name: text('name').notNull(),
  legalName: text('legal_name'),
  addressLine1: text('address_line1').notNull(),
  addressLine2: text('address_line2'),
  city: text('city').notNull(),
  stateCode: char('state_code', { length: 2 }).notNull(),
  zip: varchar('zip', { length: 10 }).notNull(),
  county: text('county'),
  formationDate: date('formation_date'),
  ein: varchar('ein', { length: 10 }),
  communityType: text('community_type').notNull().default('hoa'),
  totalUnits: integer('total_units').notNull().default(0),
  totalVotingWeight: numeric('total_voting_weight', { precision: 10, scale: 4 }).notNull().default('0'),
  fiscalYearStartMonth: smallint('fiscal_year_start_month').notNull().default(1),
  complianceConfig: jsonb('compliance_config').notNull().default({}),
  settings: jsonb('settings').notNull().default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const complianceProfiles = pgTable('compliance_profiles', {
  id: uuid('id').defaultRandom().primaryKey(),
  tenantId: bigint('tenant_id', { mode: 'number' }).references(() => tenants.id),
  scope: text('scope').notNull(),
  stateCode: char('state_code', { length: 2 }),
  communityType: text('community_type'),
  communityId: uuid('community_id').references(() => communities.id),
  priority: integer('priority').notNull().default(0),
  fineCapPerViolation: numeric('fine_cap_per_violation', { precision: 10, scale: 2 }),
  fineCapAggregate: numeric('fine_cap_aggregate', { precision: 10, scale: 2 }),
  dailyFinePermitted: boolean('daily_fine_permitted').notNull().default(true),
  dailyFineCap: numeric('daily_fine_cap', { precision: 10, scale: 2 }),
  curePeriodDays: integer('cure_period_days').notNull().default(30),
  hearingNoticeDays: integer('hearing_notice_days').notNull().default(14),
  hearingDecisionDays: integer('hearing_decision_days'),
  finingCommitteeRequired: boolean('fining_committee_required').notNull().default(false),
  certifiedMailRequired: boolean('certified_mail_required').notNull().default(false),
  lateFeeCap: numeric('late_fee_cap', { precision: 10, scale: 2 }),
  interestRateCap: numeric('interest_rate_cap', { precision: 5, scale: 4 }),
  paymentApplicationOrder: text('payment_application_order').array().notNull().default(sql`'{}'`),
  superLienEnabled: boolean('super_lien_enabled').notNull().default(false),
  superLienMonths: integer('super_lien_months'),
  enforcementRetentionYears: integer('enforcement_retention_years').notNull().default(7),
  financialRetentionYears: integer('financial_retention_years').notNull().default(7),
  rules: jsonb('rules').notNull().default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const properties = pgTable('properties', {
  id: uuid('id').defaultRandom().primaryKey(),
  tenantId: bigint('tenant_id', { mode: 'number' }).notNull().references(() => tenants.id),
  communityId: uuid('community_id').notNull().references(() => communities.id),
  addressLine1: text('address_line1').notNull(),
  addressLine2: text('address_line2'),
  city: text('city').notNull(),
  stateCode: char('state_code', { length: 2 }).notNull(),
  zip: varchar('zip', { length: 10 }).notNull(),
  lotNumber: text('lot_number'),
  unitNumber: text('unit_number'),
  building: text('building'),
  unitType: text('unit_type').notNull().default('residential'),
  squareFootage: integer('square_footage'),
  votingWeight: numeric('voting_weight', { precision: 8, scale: 4 }).notNull().default('1.0'),
  assessmentClass: text('assessment_class').notNull().default('standard'),
  parcelNumber: text('parcel_number'),
  legalDescription: text('legal_description'),
  status: text('status').notNull().default('active'),
  statusDate: date('status_date').notNull().default(sql`CURRENT_DATE`),
  amenityAccess: jsonb('amenity_access').notNull().default([]),
  customFields: jsonb('custom_fields').notNull().default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  unique().on(t.tenantId, t.communityId, t.lotNumber),
  unique().on(t.tenantId, t.communityId, t.addressLine1, t.unitNumber),
]);

export const members = pgTable('members', {
  id: uuid('id').defaultRandom().primaryKey(),
  tenantId: bigint('tenant_id', { mode: 'number' }).notNull().references(() => tenants.id),
  userId: uuid('user_id').references(() => users.id),
  firstName: text('first_name').notNull(),
  lastName: text('last_name').notNull(),
  email: text('email'),
  phone: text('phone'),
  mailingAddressLine1: text('mailing_address_line1'),
  mailingAddressCity: text('mailing_address_city'),
  mailingAddressState: char('mailing_address_state', { length: 2 }),
  mailingAddressZip: varchar('mailing_address_zip', { length: 10 }),
  memberType: text('member_type').notNull().default('owner'),
  communicationPreferences: jsonb('communication_preferences')
    .notNull()
    .default({ email: true, sms: false, push: true, mail: false }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});
